# Generated by Django 3.2.5 on 2022-03-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweeter',
            name='created',
        ),
        migrations.AlterField(
            model_name='tweeter',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='twitter.Tweeter'),
        ),
        migrations.AlterField(
            model_name='tweeter',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='twitter.Tweet'),
        ),
    ]
