# Generated by Django 3.2.5 on 2022-03-29 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=280)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('reply', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tweeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('following', models.ManyToManyField(related_name='followers', to='twitter.Tweeter')),
                ('likes', models.ManyToManyField(related_name='liked_by', to='twitter.Tweet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.tweeter'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='replied_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='twitter.tweet', verbose_name='tweet replied to'),
        ),
    ]
