# Generated by Django 3.2.5 on 2022-03-29 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20220329_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
