# Generated by Django 4.0.3 on 2022-03-31 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=280)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('reply', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tweeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=50)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='twitterclone.tweeter')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='twitterclone.tweet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitterclone.tweeter'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='replied_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='twitterclone.tweet', verbose_name='tweet replied to'),
        ),
    ]
