# Generated by Django 4.0.3 on 2022-04-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweeter',
            options={'verbose_name': 'tweeter', 'verbose_name_plural': 'tweeters'},
        ),
    ]
