# Generated by Django 4.0.3 on 2022-05-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0005_alter_tweeter_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('text', models.CharField(max_length=280, primary_key=True, serialize=False)),
                ('tweets', models.ManyToManyField(related_name='hashtags', to='twitterclone.tweet')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
    ]
